import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Map from '../components/Map'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.head}>
        <Image src="/translink_logo.png" alt="translink blue logo" height={50} width={100} />
      </header>

      <main className={styles.main}>
        <h1 style={{color: "#183152"}}>Expo line Stations</h1>
        <div className={styles.mapCont}>
        <Map/>
        </div>
      </main>

      <footer className={styles.footer}>
          <div style={{flexGrow: 2}}>
          <Image src="/translink_logo.png" alt="translink blue logo" height={80} width={200} />
            <p>Metro Vancouvers transportation network, serving residents and visitors with public transit, major roads, bridges and Trip Planning.</p>
          </div>
          <div style={{flexGrow: 1}}>
            <ul>
              <h3>Getting Around</h3>
              <p>Transit Fares</p>
              <p>Schedules</p>
              <p>Rider Info</p>
              <p>Transit Alerts</p>
            </ul>
          </div>
          <div style={{flexGrow: 1}}>
            <ul>
              <h3>Resources</h3>
              <p>Contact Us</p>
              <p>Careers</p>
            </ul>
          </div>
          <div style={{flexGrow: 1}}>
            <ul>
              <h3>Contact Us</h3>
              <p>Call us at 604.953.3333</p>
              <p>400-287 Nelsons Ct.,<br/> New Westminster, BC V3L0E7</p>
            </ul>
          </div>
      </footer>

    </div>
  )
}
